name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_PATH: ./src/CinemaKeeper.Service/CinemaKeeper.Service.csproj
  BUILD_PATH: ./build
  DOCKERFILE_PATH: ./ci/Dockerfile
  IMAGE_NAME: cinema-keeper

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
      
    - name: Build .NET project
      run: dotnet publish --configuration Release --output $BUILD_PATH $PROJECT_PATH

    - name: Build and push image
      uses: docker/build-push-action@v1
      with:
          dockerfile: ${{ env.DOCKERFILE_PATH }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nijeti/cinemakeeper/cinema-keeper
          tags: latest
