name: Build

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_PATH: ./src/CinemaKeeper.Service/CinemaKeeper.Service.csproj
  BUILD_PATH: ./build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.403
      
    - name: Build .NET project
      run: dotnet publish --configuration Release --output $BUILD_PATH $PROJECT_PATH
    
    - name: Store artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ github.sha }}
        path: ./build
