name: Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  PROJECT_DIR: ./src/CinemaKeeper.Service

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

    - name: Build and upload Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.PROJECT_DIR }}
        file: ./Dockerfile
        push: true
        tags: latest
