name: Deployment

on:
  workflow_dispatch

env:
  SCRIPTS_PATH: ./ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd $SCRIPTS_PATH
      
      - name: Copy deployment scripts to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          target: ${{ secrets.SERVER_DEPLOY_PATH }}
          source: "$./deploy.sh,./docker-compose.yaml"

      - name: Execute deployment script
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_KEY }}
          script: ./deploy.sh ${{ secrets.SERVER_DEPLOY_PATH }}
