name: Validate

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  PROJECT_DIR: ./src/CinemaKeeper.Service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: dotnet build ${{ env.PROJECT_DIR }}
    