name: Validate

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  SOURCE_DIR: ./src
  SLN_NAME: CinemaKeeper.sln
  PROJECT_DIR: ./src/CinemaKeeper.Service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 3.1.x

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: 5.0.x

      - name: Restore tools
        working-directory: ${{ env.SOURCE_DIR }}
        run: dotnet tool restore

      - name: Restore project dependencies
        working-directory: ${{ env.SOURCE_DIR }}
        run: dotnet restore

      - name: Run inspection
        working-directory: ${{ env.SOURCE_DIR }}
        run: dotnet tool run jb inspectcode ${{ env.SLN_NAME }} -s=Hint -o="inspection-results.xml"

      - uses: glassechidna/resharper-action@master
        with:
          report: ${{ env.SOURCE_DIR }}/inspection-results.xml

      - name: Upload inspection results
        uses: actions/upload-artifact@v2
        with:
          name: 'Inspection results'
          path: 'src/inspection-results.xml'

      - name: Build
        run: dotnet build ${{ env.PROJECT_DIR }}
